"""added cloud_id to media table to store outcheck photo id

Revision ID: 16c7c260a32a
Revises: 6f28cae76607
Create Date: 2022-12-17 20:24:18.096822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16c7c260a32a'
down_revision = '6f28cae76607'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('cloud_file_id', sa.String(length=35), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media', 'cloud_file_id')
    # ### end Alembic commands ###
